/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

plugins {
    id 'java'
    alias(libs.plugins.spotless)
}

def javadocExecutable = "${System.properties['java.home']}/bin/javadoc"

task testApiDoclet(type: Exec) {
    workingDir '.'
    commandLine 'python3', file('src/test/resources/apidoc_test.py'),
        '--javadoc', javadocExecutable,
        '--doclet-jar', jar.outputs.files.singleFile.absolutePath,
        '--java-root', file('src/test/fake_root'),
        '--out-dir', "${buildDir}/tmp",
        '--expected', file('src/test/resources/expected-doclet-output.txt'),
        '--expected-map', file('src/test/resources/expected-map-output.txt')
}

testApiDoclet.dependsOn jar

test.dependsOn testApiDoclet

spotless {
    lineEndings = com.diffplug.spotless.LineEnding.UNIX
    java {
        googleJavaFormat(libs.versions.google.java.format.get())
    }
}

test.dependsOn tasks.findByName("spotlessCheck")

configurations {
    docletJar
}

artifacts {
    docletJar jar
}
